version: '2'

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: env

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    depends_on:
      - postgres
      #- redis
    command: /gunicorn.sh
    env_file: env
    volumes:
      - staticfiles:/app/staticfiles

  nginx:
    build: ./compose/nginx
    depends_on:
      - django
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - staticfiles:/static

  #redis:
  #  image: redis:3.0

volumes:
  postgres_data: {}
  postgres_backup: {}
  staticfiles: {}
