version: '2'

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: env
    restart: always

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    depends_on:
      - postgres
    command: /gunicorn.sh
    volumes:
      - /ulpa/media:/app/ulpa/media
      - /ulpa/static:/app/staticfiles/
    env_file: env
    restart: always

  # Yao Pan <yao.pan@unimelb.edu.au> provided this Postfix image or you could build one yourself
  postfix:
    image: "docker.eresearch.unimelb.edu.au/infrastructure/postfix:alpine"
    environment:
      - HOSTNAME=ulpa-dev.eresearch.unimelb.edu.au
      - DOMAIN=ulpa-dev.eresearch.unimelb.edu.au
      - RELAYNETS=172.18.0.0/24
    restart: always

volumes:
  postgres_data: {}
  postgres_backup: {}
