version: '2'

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: env
    restart: always

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    depends_on:
      - postgres
    command: /gunicorn.sh
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - django_media:/app/ulpa/media
    env_file: env
    restart: always

volumes:
  postgres_data: {}
  postgres_backup: {}
  django_media: {}
